# Generated by Django 4.1.4 on 2022-12-30 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('publish_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Cast',
                'verbose_name_plural': 'Casts',
                'db_table': 'cast',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('runtime', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=255)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movie',
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['id'], name='movie_id_1793f3_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movie_title_d74866_idx'),
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cast', to='movie_cast.movie'),
        ),
        migrations.AddIndex(
            model_name='cast',
            index=models.Index(fields=['id'], name='cast_id_d3d97a_idx'),
        ),
        migrations.AddIndex(
            model_name='cast',
            index=models.Index(fields=['movie'], name='cast_movie_i_77520e_idx'),
        ),
    ]
